# Generated by Django 5.2 on 2025-08-10 14:34

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("membership_type", models.CharField(max_length=50)),
                ("join_date", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
